vich_uploader:
    db_driver: orm

    mappings:
        personnes:
            uri_prefix: /images/personnes
            upload_destination: '%kernel.project_dir%/public/images/personnes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
